import FeatureTopology.Graph

/- This file is regenerated by `python scripts/research.py export-lean`.
   Default graph: an explicit four-cycle, not a trained-network claim. -/
namespace FeatureTopology.Generated

def certificateGraph : FeatureTopology.FiniteGraph :=
  ⟨4, [(0, 1), (0, 3), (1, 2), (2, 3)]⟩

theorem certificate_graph_checked :
    FeatureTopology.checkGraph certificateGraph 1 1 = true := by decide

end FeatureTopology.Generated
